config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static#index'
  get 'signup' => 'users#new'
  get '/books' => 'books#index'
  post '/books' => 'books#show'
  get '/users/:id/books/list' => 'books#list'
  get '/books/create' => 'books#create'
  match '/login', :controller => :sessions, :to => :create, :via => :post
  match '/login', :controller => :sessions, :to => :new, :via => :get
  delete '/logout'  => 'sessions#destroy'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  belongs_to :playlist
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :books
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def list
    @books = Book.all
  end
  
  def show
    input = params['search']
    search = input.downcase.tr(" ", "_")
    apikey = "AIzaSyBQafM1TXCfHIVMdfB340ozGS7WFhaj5DA"
    base_url = "https://www.googleapis.com/books/v1/volumes?q=" + search +"+inauthor:keyes&key="+ apikey
    res = HTTParty.get(base_url)
    @result = JSON.parse(res.body)
    @searched = input
  end
  
  def delete
    
  end

  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def book_params
    params.require(:book).permit(:thumbnail, :title, :author)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
      log_out
      redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div id="books">
	<div class="col-xs-10 col-sm-4 col-md-6">
		<h1>Search books</h1>
		<%= form_tag("/books", method: "post", class: "navbar-form navbar-left") do %>
		<%= label_tag(:myform, "Search for:") %>
		<%= text_field_tag(:search) %>
		<%= submit_tag("Search", :class => "btn btn-success btn-small") %>
		<% end %>
	</div>
</div>

app/views/books/list.html.erb
<% @books.each do |book| %>
	<%= book %>
<% end %>

app/views/books/show.html.erb
<div id="books">
	<h3>Search Result for: <%= @searched %></h3>
	<div class="bs-example">
		<table class="table">
			<thead>
				<tr>
					<th>Thumbnail</th>
					<th>Title</th>
					<th>Author</th>
					<th>Description</th>
				</tr>
			</thead>
  			<tbody>
				<% if !@result['items'].nil? %>
					<% @result['items'].each do |book| %>
					<tr>
						<th><a href="/books/create"><%= image_tag book['volumeInfo']['imageLinks']['thumbnail'], :alt => "book_image" %></a></th>
						<th><%= book['volumeInfo']['title']%></th>
						<th>
							<%= book['volumeInfo']['authors'].join(", ") %>
						</th>
						<th><%= book['volumeInfo']['description']%></th>
					</tr>
					<% end %>
				<% else %>
				<tr>
					<th>"No results found"</th>
				</tr>
				<% end %>
  			</tbody>
		</table>
	</div>
</div>

app/views/layouts/_footer.html.erb
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; <a href="www.sohyeonlee.me">Sohyeon Lee</a> 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </footer>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<div class="logo"><a href="/">BH</a></div>
                <ul class="nav navbar-nav navbar-right">
					
					<% if logged_in? %>
							<li><%= link_to "Log Out", logout_path %></li>
							<li class="dropdown">
								<%= link_to "Profile", current_user, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %>
								<ul class="dropdown-menu" role="menu">
									<li><%= link_to "Update", edit_user_path(current_user)%></li>
							        <li><%= link_to "My Page", user_path(current_user) %></li>
							        <li class="divider"></li>
									
							        <li><%= link_to "Log out", logout_path, method: "delete" %></li>			         
									</ul>
								</li>
					<% else %>
						<li><%= link_to "Join", new_user_path %></li>
						<li><%= link_to "Log In", login_path %></li>
					<% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookHUB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/users/new.html.erb
<div class="col-xs-12 col-sm-12 col-md-12">
	<div class="row">
	        <div class="col-md-12">
	            <div class="pr-wrap">
	                <div class="pass-reset">
	                    <label>
	                        Enter the email you signed up with</label>
	                    <input type="email" placeholder="Email" />
	                    <input type="submit" value="Submit" class="pass-reset-submit btn btn-success btn-sm" />
	                </div>
	            </div>
	            <div class="wrap">
	                <p class="form-title"> Sign Up</p>
						<%=form_for(@user, :html => {:class => 'signup'}, :url => {:action => :create}) do |f| %>
						<%=f.label :username %>
						<%=f.text_field :name, :id => "username" %>
						<%=f.label :email %>
						<%=f.text_field :email, :id => "email"%>
						<%=f.label :password %>
						<%=f.password_field :password %>
						<%=f.label :password_confirmation %>
						<%=f.password_field :password_confirmation %>
						<%=f.submit "Create my account", class: "btn btn-success btn-sm" %>
					<% end %>
	            </div>
	        </div>
		</div>
	</div>

app/views/users/show.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container" style="margin-top: 20px; margin-bottom: 20px;">
	<div class="row panel">
		<div class="col-md-4 bg_blur ">
    	    <%= link_to "See my list", user_path + "/books/list", :class =>"follow_btn hidden-xs" %>
		</div>
        <div class="col-md-8  col-xs-12">
           <img src="http://lorempixel.com/output/people-q-c-100-100-1.jpg" class="img-thumbnail picture hidden-xs" />
           <img src="http://lorempixel.com/output/people-q-c-100-100-1.jpg" class="img-thumbnail visible-xs picture_mob" />
           <div class="header">
                <h1><%= @user.name %></h1>
                <h4><%= @user.email %></h4>
                <span>
"There is no friend as loyal as a book -- Ernest Hemingway"</span>
           </div>
        </div>
    </div>   
    
	<div class="row nav">    
        <div class="col-md-4"></div>
        <div class="col-md-8 col-xs-12" style="margin: 0px;padding: 0px;">
            <a href="/books"><div class="col-md-4 col-xs-4 well"><i class="fa fa-heart-o fa-lg"></i>Search Books</div></a>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-thumbs-o-up fa-lg"></i> Write reviews</div>
        </div>
    </div>
</div>